// 3-vue-ts/src/components/SearchBar/SearchBar.vue
<template>
  <div class="searchbar-styled">
    <input type="search" className="searchbar-input" :placeholder="placeholder" @keyup="(e: any)=> setQuery(e.target.value)" />
    <img src="/icons/search-icon.svg" alt="" class="searchbar-icon" />
  </div>
</template>

<script lang="ts" src="./SearchBar.script.ts" />
<style lang="scss" scoped src="./SearchBar.styles.scss" />

// 2-react-ts/src/components/SearchBar/index.tsx
// Style imports
import './styles.scss';

interface SearchBarProps {
    placeholder: string;
    setQuery: (val: string) => void;
}

/**
 * SearchBar component
 */
export const SearchBar = ({
    placeholder,
    setQuery
}: SearchBarProps) => {

    /**
     * Method to render searchbar component
     * @returns {React.JSXElement}
     */
    return (
        <div className="searchbar-styled">
            <input
                type="search"
                className="searchbar-input"
                placeholder={placeholder}
                onChange={(e) => setQuery(e.target.value)}
            />
            <img
                src="/icons/search-icon.svg"
                alt=""
                className="searchbar-icon"
            />
        </div>
    );
};
